# netlify.toml

[build]
  command = "yarn install --frozen-lockfile && yarn build"
  publish = ".next"
  functions = "src/functions"  # Optional: if you have Netlify Functions

[build.environment]
  NODE_VERSION = "20.17.0"  # Use a stable LTS version compatible with Next.js
  NPM_NODEJS_VERSION = "20"  # Optional: force npm to use correct Node version
  NEXT_PUBLIC_SITE_URL = "https://gymapp-khetech.netlify.app"   # Optional: useful for auth, etc.

[dev]
  command = "yarn dev"
  port = 3000
  publish = "public"

[context.production.environment]
  ENVIRONMENT = "production"

[context.deploy-preview]
  environment = "preview"

[context.branch-deploy]
  environment = "staging"