import Providers from "@/components/common/Providers";
import { SessionProvider } from '@/context/session-context'; // Add this import
import { getSession } from "@/lib/authentication";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { SonnerProvider } from "@/components/ui/sonner-provider";
import "@/public/icons.css";
import "@/public/iconss.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "PayZhe",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch session server-side
  const session = await getSession();

  return (
    <html lang="en" className="scrollbar-stylish">
      <head><meta name="facebook-domain-verification" content="q8dyybm29donnk8yhijffop1stqxn6" /></head>
      <body className={cn("antialiased max-w-lg mx-auto", inter.className)}>
        {/* Wrap everything with SessionProvider */}
        <SessionProvider initialSession={session}>
          {children}
          <Providers />
          <SonnerProvider
            position="top-center"
            closeButton={true}
            richColors={false}
            toastOptions={{
              duration: 2000,
            }}
          />
        </SessionProvider>
      </body>
    </html>
  );
}