name: Build & Deploy to VPS

on:
  push:
    branches:
      - deploytest  # Only trigger on push to 'production' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm build

    - name: Archive production build
      run: |
        mkdir deploy
        cp -r .next package.json npm.lock public deploy/
        cd deploy
        tar -czf ../app.tar.gz .

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ec2-35-170-191-44.compute-1.amazonaws.com >> ~/.ssh/known_hosts

    - name: Upload build to VPS
      run: |
        scp -i ~/.ssh/id_ed25519 app.tar.gz ubuntu@ec2-35-170-191-44.compute-1.amazonaws.com:/home/ubuntu/apps/frontend

    - name: Deploy on VPS
      run: |
        ssh -i ~/.ssh/id_ed25519 ubuntu@ec2-35-170-191-44.compute-1.amazonaws.com << 'EOF'
          cd /var/www/your-app
          rm -rf .next public node_modules
          tar -xzf app.tar.gz
          rm app.tar.gz
          npm install --production
          npx pm2 restart frontend
        EOF
